### ISSUE TITLE
Setup Own dev env on local

### ISSUE THREAD

**Issue by riseshia** [riseshia/Bonghwa#495]
## ToDo

- [x] Enable to run server via docker
- [x] Create new normal user(ref: README)
- [x] Play with Dev Server
- [ ] Solve #481

Let me now when you are in trouble.
